// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJE-LSbrDxmy9n-rvQ5Ti5gaW9wTPVL08',
    appId: '1:904641400932:web:ddad50d62d699492e90f71',
    messagingSenderId: '904641400932',
    projectId: 'fiyatatlas',
    authDomain: 'fiyatatlas.firebaseapp.com',
    storageBucket: 'fiyatatlas.firebasestorage.app',
    measurementId: 'G-SZMEFQJRKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP-pe4Vul7rcNtB7X6EeZWa3s4xtEMM4E',
    appId: '1:904641400932:android:df35ea81d8a7cb79e90f71',
    messagingSenderId: '904641400932',
    projectId: 'fiyatatlas',
    storageBucket: 'fiyatatlas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQyaeVr6stlYTlnyPc59nBAbbda1oWBuU',
    appId: '1:904641400932:ios:21e87d394fcb9d39e90f71',
    messagingSenderId: '904641400932',
    projectId: 'fiyatatlas',
    storageBucket: 'fiyatatlas.firebasestorage.app',
    androidClientId:
        '904641400932-u6aa57np0viaq0oiomvnoi033jd08v30.apps.googleusercontent.com',
    iosClientId:
        '904641400932-er5dh8upr4r2d15f15hfr59ilnasfbu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiyatatlas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQyaeVr6stlYTlnyPc59nBAbbda1oWBuU',
    appId: '1:904641400932:ios:21e87d394fcb9d39e90f71',
    messagingSenderId: '904641400932',
    projectId: 'fiyatatlas',
    storageBucket: 'fiyatatlas.firebasestorage.app',
    androidClientId:
        '904641400932-u6aa57np0viaq0oiomvnoi033jd08v30.apps.googleusercontent.com',
    iosClientId:
        '904641400932-er5dh8upr4r2d15f15hfr59ilnasfbu5.apps.googleusercontent.com',
    iosBundleId: 'com.example.fiyatatlas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJE-LSbrDxmy9n-rvQ5Ti5gaW9wTPVL08',
    appId: '1:904641400932:web:9a8d7f32e02ce4b3e90f71',
    messagingSenderId: '904641400932',
    projectId: 'fiyatatlas',
    authDomain: 'fiyatatlas.firebaseapp.com',
    storageBucket: 'fiyatatlas.firebasestorage.app',
    measurementId: 'G-DG33Z4MLDK',
  );
}
