import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';
import 'firebase_options.dart';

import 'app.dart';
// Legacy State - transitioning to Riverpod
import 'package:provider/provider.dart' as legacy_provider;
import 'app_state.dart';

import 'core/shared_providers.dart';
import 'features/price_log/data/models/price_log_model.dart';
import 'features/price_log/data/sync/sync_manager.dart';
import 'features/price_log/presentation/providers/submit_price_log_provider.dart';

// Sync Provider
final syncManagerProvider = Provider<PriceLogSyncManager>((ref) {
  return PriceLogSyncManager(
    localDataSource: ref.watch(priceLogLocalDataSourceProvider),
    remoteDataSource: ref.watch(priceLogRemoteDataSourceProvider),
    networkInfo: ref.watch(networkInfoProvider),
  );
});

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize Local DB
  final dir = await getApplicationDocumentsDirectory();
  final isar = await Isar.open(
    [PriceLogModelSchema], // Generated by build_runner
    directory: dir.path,
  );
  
  runApp(
    ProviderScope(
      overrides: [
        isarProvider.overrideWithValue(isar),
      ],
      child: Consumer(
        builder: (context, ref, child) {
          // Initialize Sync Manager
          // In a real app, use a proper lifecycle manager
          ref.watch(syncManagerProvider).init();
          
          return legacy_provider.ChangeNotifierProvider(
            create: (_) => AppState(),
            child: const FiyatAtlasApp(),
          );
        },
      ),
    ),
  );
}
