// Mocks generated by Mockito 5.4.4 from annotations
// in fiyatatlas/test/features/price_log/domain/usecases/submit_price_log_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:fiyatatlas/core/error/failures.dart' as _i6;
import 'package:fiyatatlas/features/price_log/domain/entities/price_log.dart'
    as _i7;
import 'package:fiyatatlas/features/price_log/domain/repositories/price_log_repository.dart'
    as _i4;
import 'package:fiyatatlas/features/product/domain/entities/product.dart'
    as _i3;
import 'package:fiyatatlas/features/product/domain/repositories/product_repository.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProduct_1 extends _i1.SmartFake implements _i3.Product {
  _FakeProduct_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PriceLogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPriceLogRepository extends _i1.Mock
    implements _i4.PriceLogRepository {
  MockPriceLogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, void>> submitPriceLog(_i7.PriceLog? log) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitPriceLog,
          [log],
        ),
        returnValue: _i5.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #submitPriceLog,
            [log],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, List<_i7.PriceLog>>> getMyRecentLogs(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMyRecentLogs,
          [userId],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, List<_i7.PriceLog>>>.value(
                _FakeEither_0<_i6.Failure, List<_i7.PriceLog>>(
          this,
          Invocation.method(
            #getMyRecentLogs,
            [userId],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, List<_i7.PriceLog>>>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i8.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Product?> getByBarcode(String? barcode) => (super.noSuchMethod(
        Invocation.method(
          #getByBarcode,
          [barcode],
        ),
        returnValue: _i5.Future<_i3.Product?>.value(),
      ) as _i5.Future<_i3.Product?>);

  @override
  _i5.Future<_i3.Product> createIfNotExists({
    required String? barcode,
    required String? name,
    required String? brand,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createIfNotExists,
          [],
          {
            #barcode: barcode,
            #name: name,
            #brand: brand,
          },
        ),
        returnValue: _i5.Future<_i3.Product>.value(_FakeProduct_1(
          this,
          Invocation.method(
            #createIfNotExists,
            [],
            {
              #barcode: barcode,
              #name: name,
              #brand: brand,
            },
          ),
        )),
      ) as _i5.Future<_i3.Product>);
}
